### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by mediol-git** [Anonimus3400/homework-1#1]
1. Зверни увагу на теги абзацу!
2. В кінці в списку краще використати span
![image](https://user-images.githubusercontent.com/60823963/139594278-ce0340bc-075e-4213-bf99-0605b2cfd2ee.png)

**Comment by Anonimus3400** [comment]
А що такое span?

вс, 31 окт. 2021 г., 7:04 PM mediol-git ***@***.***>:

**Comment by mediol-git** [comment]
Це такий тег
